// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG66wX_rlJG5YdhKNjVq_bGYxIbbQC1OI',
    appId: '1:289133575243:web:073a42db46deb80e6ea1ce',
    messagingSenderId: '289133575243',
    projectId: 'clienteart-18f39',
    authDomain: 'clienteart-18f39.firebaseapp.com',
    storageBucket: 'clienteart-18f39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLvbEJpzygnexTWkPTCj7V3xkXsmIxT3c',
    appId: '1:289133575243:android:b8e863063c15af8d6ea1ce',
    messagingSenderId: '289133575243',
    projectId: 'clienteart-18f39',
    storageBucket: 'clienteart-18f39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCNiDOrGlUOxtha_IMDD28TFESQNto4k0',
    appId: '1:289133575243:ios:2712ca8df2359d4d6ea1ce',
    messagingSenderId: '289133575243',
    projectId: 'clienteart-18f39',
    storageBucket: 'clienteart-18f39.appspot.com',
    iosClientId: '289133575243-u5jbe8k1fl1nr7lq4345dvb7sroepbck.apps.googleusercontent.com',
    iosBundleId: 'com.example.randomDados',
  );
}
